trigger:
- main

pool:
  name: Default
  # vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      continueOnError: true
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: '$(System.DefaultWorkingDirectory)/SampleAPItest'
    - task: CmdLine@2
      displayName: Run regression tests
      inputs:
        script: 'newman run starterapis.json'
        workingDirectory: '$(System.DefaultWorkingDirectory)/SampleAPItest'